#include <stdio.h>
#include <stdlib.h>
#include "fileio/fileio.h"
#include "utils/pak.h"
#include "assetconv.h"

const char* ASSET_FILENAMES[] = {
    "system.cache",
    "sprites/sprites.spr",
    "shop/shop.spr",
    "party/party.spr",
    "scripts/ch1l1_01.dat",
    "scripts/ch1l1_02.dat",
    "scripts/ch1l2_01.dat",
    "scripts/ch1l2_02.dat",
    "scripts/ch1l2_03.dat",
    "scripts/ch1l4_01.dat",
    "scripts/ch1l4_02.dat",
    "scripts/ch2l1_01.dat",
    "scripts/ch2l1_02.dat",
    "scripts/ch2l2_01.dat",
    "scripts/ch2l2_02.dat",
    "scripts/ch3l2_01.dat",
    "scripts/ch3l3_01.dat",
    "scripts/ch3l3_02.dat",
    "scripts/ch4l3_01.dat",
    "scripts/ch4l3_02.dat",
    "scripts/fma_ch1_00.dat",
    "scripts/fma_ch1_01.dat",
    "scripts/fma_ch1_02.dat",
    "scripts/fma_ch1_03.dat",
    "scripts/fma_ch2_00.dat",
    "scripts/fma_ch2_01.dat",
    "scripts/fma_ch2_02.dat",
    "scripts/fma_ch2_03.dat",
    "scripts/fma_ch3_00.dat",
    "scripts/fma_ch3_01.dat",
    "scripts/fma_ch3_02.dat",
    "scripts/fma_ch4_00.dat",
    "scripts/fma_ch4_01.dat",
    "scripts/fma_ch4_02.dat",
    "scripts/fma_ch5_00.dat",
    "scripts/fma_ch5_01.dat",
    "scripts/fma_ch5_02.dat",
    "scripts/fma_ch6_00.dat",
    "scripts/fma_ch6_01.dat",
    "scripts/fma_ch6_02.dat",
    "scripts/fma_ch6_03.dat",
    "scripts/fma_party.dat",
    "scripts/fma_plankton.dat",
    "scripts/c1l1_celebrate.dat",
    "scripts/c1l2_celebrate.dat",
    "scripts/c1l3_celebrate.dat",
    "scripts/c1l4_celebrate.dat",
    "scripts/c2l1_celebrate.dat",
    "scripts/c2l2_celebrate.dat",
    "scripts/c2l3_celebrate.dat",
    "scripts/c2l4_celebrate.dat",
    "scripts/c3l1_celebrate.dat",
    "scripts/c3l2_celebrate.dat",
    "scripts/c3l3_celebrate.dat",
    "scripts/c3l4_celebrate.dat",
    "scripts/c4l1_celebrate.dat",
    "scripts/c4l2_celebrate.dat",
    "scripts/c4l3_celebrate.dat",
    "scripts/c4l4_celebrate.dat",
    "scripts/c5l1_celebrate.dat",
    "scripts/c5l2_celebrate.dat",
    "scripts/c5l3_celebrate.dat",
    "scripts/c5l4_celebrate.dat",
    "scripts/triggerspeech_151.dat",
    "scripts/triggerspeech_152.dat",
    "scripts/triggerspeech_153.dat",
    "scripts/triggerspeech_154.dat",
    "scripts/triggerspeech_155.dat",
    "scripts/triggerspeech_156.dat",
    "scripts/triggerspeech_157.dat",
    "scripts/triggerspeech_158.dat",
    "scripts/triggerspeech_159.dat",
    "scripts/triggerspeech_028.dat",
    "translations/swe.dat",
    "translations/dut.dat",
    "translations/ita.dat",
    "translations/ger.dat",
    "translations/id.dat",
    "translations/eng.dat",
    "music/chapter1.pxm",
    "music/chapter1.vb",
    "music/chapter1.vh",
    "music/chapter2.pxm",
    "music/chapter2.vb",
    "music/chapter2.vh",
    "music/chapter3.pxm",
    "music/chapter3.vb",
    "music/chapter3.vh",
    "music/chapter4.pxm",
    "music/chapter4.vb",
    "music/chapter4.vh",
    "music/chapter5.pxm",
    "music/chapter5.vb",
    "music/chapter5.vh",
    "music/chapter6.pxm",
    "music/chapter6.vb",
    "music/chapter6.vh",
    "music/sb_title.pxm",
    "music/sb_title.vb",
    "music/sb_title.vh",
    "music/fma.pxm",
    "music/fma.vb",
    "music/fma.vh",
    "sfx/ingame.pxm",
    "sfx/ingame.vb",
    "sfx/ingame.vh",
    "demo/demo____.dmo",
    "backdrop/credits.gfx",
    "backdrop/start1.gfx",
    "backdrop/start2.gfx",
    "backdrop/start3.gfx",
    "backdrop/start4.gfx",
    "backdrop/gameover.gfx",
    "backdrop/shop.gfx",
    "backdrop/party_backdrop.gfx",
    "backdrop/nick.gfx",
    "loadingscreens/culture.gfx",
    "loadingscreens/karate.gfx",
    "loadingscreens/monitor.gfx",
    "loadingscreens/pickles.gfx",
    "loadingscreens/pineapple.gfx",
    "loadingscreens/pizza.gfx",
    "loadingscreens/teenage.gfx",
    "loadingscreens/bootscreen.gfx",
    "memcard/memhead.bin",
    "map/map_background.gfx",
    "map/c1_l1.gfx",
    "map/c1_l2.gfx",
    "map/c1_l3.gfx",
    "map/c1_l4.gfx",
    "map/c1_fair.gfx",
    "map/c2_l1.gfx",
    "map/c2_l2.gfx",
    "map/c2_l3.gfx",
    "map/c2_l4.gfx",
    "map/c2_fair.gfx",
    "map/c3_l1.gfx",
    "map/c3_l2.gfx",
    "map/c3_l3.gfx",
    "map/c3_l4.gfx",
    "map/c3_fair.gfx",
    "map/c4_l1.gfx",
    "map/c4_l2.gfx",
    "map/c4_l3.gfx",
    "map/c4_l4.gfx",
    "map/c4_fair.gfx",
    "map/c5_l1.gfx",
    "map/c5_l2.gfx",
    "map/c5_l3.gfx",
    "map/c5_l4.gfx",
    "map/c5_fair.gfx",
    "levels/chapter01_level01.lvl",
    "levels/chapter01_level01.tex",
    "levels/chapter01_level02.lvl",
    "levels/chapter01_level02.tex",
    "levels/chapter01_level03.lvl",
    "levels/chapter01_level03.tex",
    "levels/chapter01_level04.lvl",
    "levels/chapter01_level04.tex",
    "levels/chapter02_level01.lvl",
    "levels/chapter02_level01.tex",
    "levels/chapter02_level02.lvl",
    "levels/chapter02_level02.tex",
    "levels/chapter02_level03.lvl",
    "levels/chapter02_level03.tex",
    "levels/chapter02_level04.lvl",
    "levels/chapter02_level04.tex",
    "levels/chapter03_level01.lvl",
    "levels/chapter03_level01.tex",
    "levels/chapter03_level02.lvl",
    "levels/chapter03_level02.tex",
    "levels/chapter03_level03.lvl",
    "levels/chapter03_level03.tex",
    "levels/chapter03_level04.lvl",
    "levels/chapter03_level04.tex",
    "levels/chapter04_level01.lvl",
    "levels/chapter04_level01.tex",
    "levels/chapter04_level02.lvl",
    "levels/chapter04_level02.tex",
    "levels/chapter04_level03.lvl",
    "levels/chapter04_level03.tex",
    "levels/chapter04_level04.lvl",
    "levels/chapter04_level04.tex",
    "levels/chapter05_level01.lvl",
    "levels/chapter05_level01.tex",
    "levels/chapter05_level02.lvl",
    "levels/chapter05_level02.tex",
    "levels/chapter05_level03.lvl",
    "levels/chapter05_level03.tex",
    "levels/chapter05_level04.lvl",
    "levels/chapter05_level04.tex",
    "levels/chapter06_level01.lvl",
    "levels/chapter06_level01.tex",
    "levels/chapter06_level02.lvl",
    "levels/chapter06_level02.tex",
    "levels/chapter06_level03.lvl",
    "levels/chapter06_level03.tex",
    "levels/chapter06_level04.lvl",
    "levels/chapter06_level04.tex",
    "levels/chapter06_level05.lvl",
    "levels/chapter06_level05.tex",
    "levels/fma_shadyshoals.lvl",
    "levels/fma_shadyshoals.tex",
    "levels/fma_controlroom.lvl",
    "levels/fma_controlroom.tex",
    "actors/spongebob.sbk",
    "actors/spongebob_coralblower.sbk",
    "actors/spongebob_jellylauncher.sbk",
    "actors/spongebob_net.sbk",
    "actors/spongebob_wand.sbk",
    "actors/spongebob_jellyfish.sbk",
    "actors/spongebob_glove.sbk",
    "actors/spongebob_fma.sbk",
    "actors/spongebob_fma_itemofs.sbk",
    "actors/barnacleboy.sbk",
    "actors/barnacleboy_fma_itemofs.sbk",
    "actors/krusty.sbk",
    "actors/squidward.sbk",
    "actors/gary.sbk",
    "actors/sandy.sbk",
    "actors/patrick.sbk",
    "actors/mermaidman.sbk",
    "actors/mermaidman_fma_itemofs.sbk",
    "actors/plankton.sbk",
    "actors/anenome.sbk",
    "actors/babyoctopus.sbk",
    "actors/ballblob.sbk",
    "actors/caterpillar.sbk",
    "actors/clam.sbk",
    "actors/dustdevil.sbk",
    "actors/flamingskull.sbk",
    "actors/flyingdutchman.sbk",
    "actors/ghost.sbk",
    "actors/hermitcrab.sbk",
    "actors/irondogfish.sbk",
    "actors/puffafish.sbk",
    "actors/manray.sbk",
    "actors/skeletalfish.sbk",
    "actors/spidercrab.sbk",
    "actors/spikeyanenome.sbk",
    "actors/stomper.sbk",
    "actors/giantworm.sbk",
    "actors/sharksub.sbk",
    "actors/motherjellyfish.sbk",
    "actors/seasnake.sbk"
};

char copyBuffer[2048];

void Assets_ConvertLumpToPak(const char* inFileName, const char* outFileName)
{
    sFAT lumpEntry;
    pakEntry entry;

    FILE* inFile = fopen(inFileName, "rb");
    FILE* outFile = fopen(outFileName, "wb");

    // Write header
    pakHeader header = { {'P','A','C','K'}, sizeof(pakHeader), sizeof(pakEntry) * FileEquate_MAX };
    fwrite(&header, sizeof(pakHeader), 1, outFile);
    
    // Convert table
    for (int i = 0; i < FileEquate_MAX; i++)
    {
        // Lump
        fread(&lumpEntry, sizeof(sFAT), 1, inFile);

        // Pak
        entry.offset = (lumpEntry.FilePos - 2036) + (sizeof(pakEntry) * FileEquate_MAX);
        entry.size = lumpEntry.FileSize;
        sprintf(&entry.name[0], ASSET_FILENAMES[i]);
        fwrite(&entry, sizeof(pakEntry), 1, outFile);
    }

    // Fill out the rest of the contents
    fseek(inFile, 0, SEEK_END);
    int dataSize = ftell(inFile);
    fseek(inFile, 2048, SEEK_SET);
    while (ftell(inFile) < dataSize)
    {
        fread(&copyBuffer, 2048, 1, inFile);
        fwrite(&copyBuffer, 2048, 1, outFile);
    }
    
    // Close both files
    fclose(inFile);
    fclose(outFile);
}