// SPONGEBOB Anim Header

#ifndef	__ANIM_SPONGEBOB_HEADER__
#define	__ANIM_SPONGEBOB_HEADER__


enum	ANIM_SPONGEBOB_LIST
{
	ANIM_SPONGEBOB_BUTTBOUNCEEND=0,
	ANIM_SPONGEBOB_BUTTBOUNCESTART,
	ANIM_SPONGEBOB_FALL,
	ANIM_SPONGEBOB_GETUP,
	ANIM_SPONGEBOB_HITGROUND,
	ANIM_SPONGEBOB_IDLEBREATH,
	ANIM_SPONGEBOB_JUMPEND,
	ANIM_SPONGEBOB_JUMP,
	ANIM_SPONGEBOB_RUN,
	ANIM_SPONGEBOB_RUNSTOP,
	ANIM_SPONGEBOB_RUNSTART,
	ANIM_SPONGEBOB_TEETERBACK,
	ANIM_SPONGEBOB_TEETERFRONT,
	ANIM_SPONGEBOB_SWIPE,
	ANIM_SPONGEBOB_DEATHTAR,
	ANIM_SPONGEBOB_BALLOONJUMP,
	ANIM_SPONGEBOB_BLOWBUBBLE,
	ANIM_SPONGEBOB_FIREEND,
	ANIM_SPONGEBOB_FIRESTART,
	ANIM_SPONGEBOB_IDLEWEAPON,
	ANIM_SPONGEBOB_WALK,
	ANIM_SPONGEBOB_KARATE,
	ANIM_SPONGEBOB_GETHIT,
	ANIM_SPONGEBOB_CROUCHDOWN,
	ANIM_SPONGEBOB_CROUCHUP,
	ANIM_SPONGEBOB_LOOKUP,
	ANIM_SPONGEBOB_IDLEFACEUPSIDEDOWN,
	ANIM_SPONGEBOB_IDLEBANDAID,
	ANIM_SPONGEBOB_IDLEMATURE,
	ANIM_SPONGEBOB_IDLEMOUSTACHE,
	ANIM_SPONGEBOB_IDLENOFACE,
	ANIM_SPONGEBOB_IDLEZORRO,
	ANIM_SPONGEBOB_CELEBRATE,
	ANIM_SPONGEBOB_IDLEBLINK,
	ANIM_SPONGEBOB_ELECTROCUTED,
	ANIM_SPONGEBOB_DEATHBOUNCE,
	NUM_ANIM_SPONGEBOB
};

#endif
