// SPONGEBOB_WAND Anim Header

#ifndef	__ANIM_SPONGEBOB_WAND_HEADER__
#define	__ANIM_SPONGEBOB_WAND_HEADER__


enum	ANIM_SPONGEBOB_WAND_LIST
{
	ANIM_SPONGEBOB_WAND_BUTTBOUNCEEND=0,
	ANIM_SPONGEBOB_WAND_BUTTBOUNCESTART,
	ANIM_SPONGEBOB_WAND_BLOWBUBBLE,
	ANIM_SPONGEBOB_WAND_LOOKUP,
	ANIM_SPONGEBOB_WAND_FALL,
	ANIM_SPONGEBOB_WAND_GETUP,
	ANIM_SPONGEBOB_WAND_HITGROUND,
	ANIM_SPONGEBOB_WAND_IDLEBREATH,
	ANIM_SPONGEBOB_WAND_IDLEWEAPON,
	ANIM_SPONGEBOB_WAND_JUMPEND,
	ANIM_SPONGEBOB_WAND_JUMP,
	ANIM_SPONGEBOB_WAND_RUN,
	ANIM_SPONGEBOB_WAND_RUNSTOP,
	ANIM_SPONGEBOB_WAND_RUNSTART,
	ANIM_SPONGEBOB_WAND_TEETERBACK,
	ANIM_SPONGEBOB_WAND_TEETERFRONT,
	ANIM_SPONGEBOB_WAND_DEATHTAR,
	ANIM_SPONGEBOB_WAND_GETHIT,
	ANIM_SPONGEBOB_WAND_CROUCHDOWN,
	ANIM_SPONGEBOB_WAND_CROUCHUP,
	ANIM_SPONGEBOB_WAND_CELEBRATE,
	ANIM_SPONGEBOB_WAND_IDLEBLINK,
	ANIM_SPONGEBOB_WAND_ELECTROCUTED,
	ANIM_SPONGEBOB_WAND_DEATHBOUNCE,
	NUM_ANIM_SPONGEBOB_WAND
};

#endif
