// BABYOCTOPUS Anim Header

#ifndef	__ANIM_BABYOCTOPUS_HEADER__
#define	__ANIM_BABYOCTOPUS_HEADER__


enum	ANIM_BABYOCTOPUS_LIST
{
	ANIM_BABYOCTOPUS_DIE=0,
	ANIM_BABYOCTOPUS_HEAD_BUTT,
	ANIM_BABYOCTOPUS_HIT,
	ANIM_BABYOCTOPUS_IDLE,
	ANIM_BABYOCTOPUS_INK,
	ANIM_BABYOCTOPUS_SWIM,
	ANIM_BABYOCTOPUS_TURN,
	NUM_ANIM_BABYOCTOPUS
};

#endif
