// SPONGEBOB_FMA Anim Header

#ifndef	__ANIM_SPONGEBOB_FMA_HEADER__
#define	__ANIM_SPONGEBOB_FMA_HEADER__


enum	ANIM_SPONGEBOB_FMA_LIST
{
	ANIM_SPONGEBOB_FMA_FIXTV=0,
	ANIM_SPONGEBOB_FMA_GIVEEND,
	ANIM_SPONGEBOB_FMA_GIVESTART,
	ANIM_SPONGEBOB_FMA_IDEA,
	ANIM_SPONGEBOB_FMA_QUICKEXIT,
	ANIM_SPONGEBOB_FMA_SHOUT,
	ANIM_SPONGEBOB_FMA_STUMBLE,
	ANIM_SPONGEBOB_FMA_THROW,
	ANIM_SPONGEBOB_FMA_PARTY,
	NUM_ANIM_SPONGEBOB_FMA
};

#endif
