// SPIKEYANENOME Anim Header

#ifndef	__ANIM_SPIKEYANENOME_HEADER__
#define	__ANIM_SPIKEYANENOME_HEADER__


enum	ANIM_SPIKEYANENOME_LIST
{
	ANIM_SPIKEYANENOME_BODY=0,
	NUM_ANIM_SPIKEYANENOME
};

#endif
