// FLYINGDUTCHMAN Anim Header

#ifndef	__ANIM_FLYINGDUTCHMAN_HEADER__
#define	__ANIM_FLYINGDUTCHMAN_HEADER__


enum	ANIM_FLYINGDUTCHMAN_LIST
{
	ANIM_FLYINGDUTCHMAN_FIREATTACK=0,
	ANIM_FLYINGDUTCHMAN_FLY,
	ANIM_FLYINGDUTCHMAN_GETHIT,
	ANIM_FLYINGDUTCHMAN_DEATH,
	NUM_ANIM_FLYINGDUTCHMAN
};

#endif
