// SPIDERCRAB Anim Header

#ifndef	__ANIM_SPIDERCRAB_HEADER__
#define	__ANIM_SPIDERCRAB_HEADER__


enum	ANIM_SPIDERCRAB_LIST
{
	ANIM_SPIDERCRAB_BITE=0,
	ANIM_SPIDERCRAB_HIT,
	ANIM_SPIDERCRAB_IDLE,
	ANIM_SPIDERCRAB_JUMP,
	ANIM_SPIDERCRAB_RUN,
	NUM_ANIM_SPIDERCRAB
};

#endif
