// HERMITCRAB Anim Header

#ifndef	__ANIM_HERMITCRAB_HEADER__
#define	__ANIM_HERMITCRAB_HEADER__


enum	ANIM_HERMITCRAB_LIST
{
	ANIM_HERMITCRAB_DIE=0,
	ANIM_HERMITCRAB_IDLE,
	ANIM_HERMITCRAB_ROLLATTACK,
	ANIM_HERMITCRAB_SCUTTLE,
	NUM_ANIM_HERMITCRAB
};

#endif
