// SPONGEBOB_GLOVE Anim Header

#ifndef	__ANIM_SPONGEBOB_GLOVE_HEADER__
#define	__ANIM_SPONGEBOB_GLOVE_HEADER__


enum	ANIM_SPONGEBOB_GLOVE_LIST
{
	ANIM_SPONGEBOB_GLOVE_KARATE=0,
	NUM_ANIM_SPONGEBOB_GLOVE
};

#endif
