// CATERPILLAR Anim Header

#ifndef	__ANIM_CATERPILLAR_HEADER__
#define	__ANIM_CATERPILLAR_HEADER__


enum	ANIM_CATERPILLAR_LIST
{
	ANIM_CATERPILLAR_CRAWL=0,
	ANIM_CATERPILLAR_DIE,
	NUM_ANIM_CATERPILLAR
};

#endif
