// PUFFAFISH Anim Header

#ifndef	__ANIM_PUFFAFISH_HEADER__
#define	__ANIM_PUFFAFISH_HEADER__


enum	ANIM_PUFFAFISH_LIST
{
	ANIM_PUFFAFISH_PUFFUPIDLE=0,
	ANIM_PUFFAFISH_SWIM,
	ANIM_PUFFAFISH_TURN,
	NUM_ANIM_PUFFAFISH
};

#endif
