// IRONDOGFISH Anim Header

#ifndef	__ANIM_IRONDOGFISH_HEADER__
#define	__ANIM_IRONDOGFISH_HEADER__


enum	ANIM_IRONDOGFISH_LIST
{
	ANIM_IRONDOGFISH_GETHIT=0,
	ANIM_IRONDOGFISH_IDLE,
	ANIM_IRONDOGFISH_PUNCH,
	ANIM_IRONDOGFISH_TAILSMASH,
	ANIM_IRONDOGFISH_WALK,
	ANIM_IRONDOGFISH_DIE,
	NUM_ANIM_IRONDOGFISH
};

#endif
