// SPONGEBOB_FMA_ITEMOFS Anim Header

#ifndef	__ANIM_SPONGEBOB_FMA_ITEMOFS_HEADER__
#define	__ANIM_SPONGEBOB_FMA_ITEMOFS_HEADER__


enum	ANIM_SPONGEBOB_FMA_ITEMOFS_LIST
{
	ANIM_SPONGEBOB_FMA_ITEMOFS_IDLEBREATH=0,
	ANIM_SPONGEBOB_FMA_ITEMOFS_QUICKEXIT,
	ANIM_SPONGEBOB_FMA_ITEMOFS_RUN,
	ANIM_SPONGEBOB_FMA_ITEMOFS_STUMBLE,
	NUM_ANIM_SPONGEBOB_FMA_ITEMOFS
};

#endif
