// SPONGEBOB_NET Anim Header

#ifndef	__ANIM_SPONGEBOB_NET_HEADER__
#define	__ANIM_SPONGEBOB_NET_HEADER__


enum	ANIM_SPONGEBOB_NET_LIST
{
	ANIM_SPONGEBOB_NET_BUTTBOUNCEEND=0,
	ANIM_SPONGEBOB_NET_BUTTBOUNCESTART,
	ANIM_SPONGEBOB_NET_FALL,
	ANIM_SPONGEBOB_NET_GETUP,
	ANIM_SPONGEBOB_NET_HITGROUND,
	ANIM_SPONGEBOB_NET_IDLEBREATH,
	ANIM_SPONGEBOB_NET_JUMPEND,
	ANIM_SPONGEBOB_NET_JUMP,
	ANIM_SPONGEBOB_NET_RUN,
	ANIM_SPONGEBOB_NET_RUNSTOP,
	ANIM_SPONGEBOB_NET_RUNSTART,
	ANIM_SPONGEBOB_NET_TEETERBACK,
	ANIM_SPONGEBOB_NET_TEETERFRONT,
	ANIM_SPONGEBOB_NET_SWIPE,
	ANIM_SPONGEBOB_NET_DEATHTAR,
	ANIM_SPONGEBOB_NET_GETHIT,
	ANIM_SPONGEBOB_NET_CROUCHDOWN,
	ANIM_SPONGEBOB_NET_CROUCHUP,
	ANIM_SPONGEBOB_NET_LOOKUP,
	ANIM_SPONGEBOB_NET_IDLEWEAPON,
	ANIM_SPONGEBOB_NET_CELEBRATE,
	ANIM_SPONGEBOB_NET_IDLEBLINK,
	ANIM_SPONGEBOB_NET_ELECTROCUTED,
	ANIM_SPONGEBOB_NET_DEATHBOUNCE,
	NUM_ANIM_SPONGEBOB_NET
};

#endif
