// MERMAIDMAN Anim Header

#ifndef	__ANIM_MERMAIDMAN_HEADER__
#define	__ANIM_MERMAIDMAN_HEADER__


enum	ANIM_MERMAIDMAN_LIST
{
	ANIM_MERMAIDMAN_HIDE=0,
	ANIM_MERMAIDMAN_IDLE,
	ANIM_MERMAIDMAN_SIT,
	ANIM_MERMAIDMAN_SITASLEEP,
	NUM_ANIM_MERMAIDMAN
};

#endif
