// GIANTWORM Anim Header

#ifndef	__ANIM_GIANTWORM_HEADER__
#define	__ANIM_GIANTWORM_HEADER__


enum	ANIM_GIANTWORM_LIST
{
	ANIM_GIANTWORM_BODYSTATIC=0,
	ANIM_GIANTWORM_HEADSTATIC,
	ANIM_GIANTWORM_ARMS,
	ANIM_GIANTWORM_TAIL,
	NUM_ANIM_GIANTWORM
};

#endif
