// MERMAIDMAN_FMA_ITEMOFS Anim Header

#ifndef	__ANIM_MERMAIDMAN_FMA_ITEMOFS_HEADER__
#define	__ANIM_MERMAIDMAN_FMA_ITEMOFS_HEADER__


enum	ANIM_MERMAIDMAN_FMA_ITEMOFS_LIST
{
	ANIM_MERMAIDMAN_FMA_ITEMOFS_SITASLEEP=0,
	NUM_ANIM_MERMAIDMAN_FMA_ITEMOFS
};

#endif
