// SEASNAKE Anim Header

#ifndef	__ANIM_SEASNAKE_HEADER__
#define	__ANIM_SEASNAKE_HEADER__


enum	ANIM_SEASNAKE_LIST
{
	ANIM_SEASNAKE_BODY1STATIC=0,
	ANIM_SEASNAKE_BODY2STATIC,
	ANIM_SEASNAKE_BODY3STATIC,
	ANIM_SEASNAKE_TAILSTATIC,
	ANIM_SEASNAKE_HEADSNAP,
	NUM_ANIM_SEASNAKE
};

#endif
