// MOTHERJELLYFISH Anim Header

#ifndef	__ANIM_MOTHERJELLYFISH_HEADER__
#define	__ANIM_MOTHERJELLYFISH_HEADER__


enum	ANIM_MOTHERJELLYFISH_LIST
{
	ANIM_MOTHERJELLYFISH_STATIC=0,
	NUM_ANIM_MOTHERJELLYFISH
};

#endif
