// BARNACLEBOY Anim Header

#ifndef	__ANIM_BARNACLEBOY_HEADER__
#define	__ANIM_BARNACLEBOY_HEADER__


enum	ANIM_BARNACLEBOY_LIST
{
	ANIM_BARNACLEBOY_IDLE=0,
	ANIM_BARNACLEBOY_GIVEEND,
	ANIM_BARNACLEBOY_GIVESTART,
	ANIM_BARNACLEBOY_SIT,
	ANIM_BARNACLEBOY_SITLOOKLEFT,
	ANIM_BARNACLEBOY_HIDE,
	ANIM_BARNACLEBOY_UNHIDE,
	ANIM_BARNACLEBOY_UNHIDEIDLE,
	ANIM_BARNACLEBOY_SITASLEEP,
	ANIM_BARNACLEBOY_RUBHEAD,
	NUM_ANIM_BARNACLEBOY
};

#endif
