// BARNACLEBOY_FMA_ITEMOFS Anim Header

#ifndef	__ANIM_BARNACLEBOY_FMA_ITEMOFS_HEADER__
#define	__ANIM_BARNACLEBOY_FMA_ITEMOFS_HEADER__


enum	ANIM_BARNACLEBOY_FMA_ITEMOFS_LIST
{
	ANIM_BARNACLEBOY_FMA_ITEMOFS_IDLE=0,
	ANIM_BARNACLEBOY_FMA_ITEMOFS_RUBHEAD,
	ANIM_BARNACLEBOY_FMA_ITEMOFS_SITLOOKLEFT,
	ANIM_BARNACLEBOY_FMA_ITEMOFS_UNHIDE,
	NUM_ANIM_BARNACLEBOY_FMA_ITEMOFS
};

#endif
