// SKELETALFISH Anim Header

#ifndef	__ANIM_SKELETALFISH_HEADER__
#define	__ANIM_SKELETALFISH_HEADER__


enum	ANIM_SKELETALFISH_LIST
{
	ANIM_SKELETALFISH_IDLE=0,
	ANIM_SKELETALFISH_SWIM,
	NUM_ANIM_SKELETALFISH
};

#endif
