// SHARKSUB Anim Header

#ifndef	__ANIM_SHARKSUB_HEADER__
#define	__ANIM_SHARKSUB_HEADER__


enum	ANIM_SHARKSUB_LIST
{
	ANIM_SHARKSUB_CHOMP=0,
	ANIM_SHARKSUB_DEATH,
	ANIM_SHARKSUB_SPRINTOPEN,
	ANIM_SHARKSUB_SWIM,
	ANIM_SHARKSUB_SWIPE,
	NUM_ANIM_SHARKSUB
};

#endif
