// FMA_SHADYSHOALS Info Header

#ifndef	__FMA_SHADYSHOALS_INF_HEADER__
#define	__FMA_SHADYSHOALS_INF_HEADER__


enum	FMA_SHADYSHOALS_INF
{
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SPONGEBOB		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_BARNACLEBOY		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_GARY		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_KRUSTY		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_MERMAIDMAN		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_PATRICK		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SANDY		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SQUIDWARD		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_PLANKTON		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_MOTHERJELLYFISH		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_ANENOME_LEVEL1		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SPIKEYANENOME		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_ANENOME_LEVEL3		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_BABYOCTOPUS		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_BALLBLOB		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_BOOGERMONSTER		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_CATERPILLAR		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_JUMPINGCLAM		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_STATICCLAM		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_EYEBALL		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_FLAMINGSKULL		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_FLYINGDUTCHMAN		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_GHOST		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_GIANTWORM		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_HERMITCRAB		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_IRONDOGFISH		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_PUFFAFISH		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SEASNAKE		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SHARKMAN		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SHARKSUB		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SKELETALFISH		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SPIDERCRAB		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SQUIDDART		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_STOMPER		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_DUSTDEVIL		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SPIDERCRABSPAWNER		=0,
	FMA_SHADYSHOALS_INF_TOTAL_ACTOR_SHELL		=0,
};

#endif
