#ifndef __SPR_PARTY_H__
#define __SPR_PARTY_H__
/* Palette defines */
#define PAL_BALLOONS1 32
/* Frame defines */
#define FRM_BALLOONS1 0
#define FRM_BALLOONS2 1
#define FRM_BALLOONS3 2
#define FRM_BALLOONS4 3
#define FRM_BALLOONS5 4
#define FRM_BALLOONS6 5
#define FRM_BALLOONS7 6
#define FRM_BALLOONS8 7
#define FRM_BANNER1 8
#define FRM_BANNER2 9
#define FRM_BANNER3 10
#define FRM_BANNER4 11
#define FRM_BANNER5 12
#define FRM_BANNER6 13
#define FRM_BANNER7 14
#define FRM_BIGCAKE 15
#define FRM_CHERRYCAKES 16
#define FRM_CUCUMBERSARNIES 17
#define FRM_JELLY 18
#define FRM_PRESSIES1 19
#define FRM_PRESSIES2 20
#define FRM_PRESSIES3 21
#define FRM_PRESSIES4 22
#define FRM_SLICEOFCAKE 23
#define FRM_SOFTTOYS1 24
#define FRM_SOFTTOYS2 25
#define FRM_SOFTTOYS3 26
#define FRM_STREAMERS1 27
#define FRM_STREAMERS2 28
#define FRM_STREAMERS3 29
#define FRM_STREAMERS4 30
#define FRM_STREAMERS5 31
#define FRM_STREAMERS6 32
#define FRM_TABLEFRONT1 33
#define FRM_TABLEFRONT2 34
#define FRM_TABLEFRONT3 35
#define FRM_TABLEFRONT4 36
#define FRM_TABLEFRONT5 37
#define FRM_TABLEFRONT6 38
#define FRM_TABLEFRONT7 39
#define FRM_TABLESIDE1 40
#define FRM_TABLESIDE2 41
#define FRM_TABLESIDE3 42
#endif 
